import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/src/Providers.jsx";
import AuthInitializer from "@/src/hoc/AuthInitializer";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nobi",
  description: "Generated by create next app",
};
const queryClient = new QueryClient();
export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <AuthInitializer>
            <div
              style={{
                background: "#101010",
                color: "#16171c",
              }}
            >
              <ToastContainer
                hideProgressBar={true}
                position="top-center"
                autoClose={4000}
                limit={2}
              />
            </div>
            {/* <QueryClientProvider client={queryClient}> */}
            {children}
            {/* </QueryClientProvider> */}
          </AuthInitializer>
        </body>
      </html>
    </Providers>
  );
}
